### ISSUE TITLE
Lot of promises remain unresolved

### ISSUE THREAD

**Issue by bitliner** [medikoo/deferred#27]
I'm using deferred.monitor() to monitor all the promises that are still unresolved after 20 seconds the end of the program

This is the code:

```
deferred.monitor();
deferred.monitor(20000, function (err) {
    console.log('PROMISE',err.stack)
});
```

The problem is that a lot of promises remain unresolved, but they shoudn't (the line def.resolve is executed).

Someone of them rejects an error, but in this case they should be considered as resolved, shoudn't they?

May be there some causes of this behaviour?

PS: hoping this is the reight place where I can talk about this topic

**Comment by anjil** [comment]
I used the same code shared in the documentation and even that give 2 unresolved promises. The sample is as below:

```javascript
var deferred = require('deferred');

deferred.profile();

var delay = function (fn, timeout) {
  return function () {
    var def = deferred(), self = this, args = arguments;
 
    setTimeout(function () {
      var value;
      try {
        value = fn.apply(self, args);
      } catch (e) {
        def.reject(e);
        return;
      }
      def.resolve(value);
    }, timeout);
 
    return def.promise;
  };
};
 
var delayedAdd = delay(function (a, b) {
  return a + b;
}, 100);
 
var resultPromise = delayedAdd(2, 3);
 
console.log(deferred.isPromise(resultPromise)); // true
 
resultPromise(function (value) {
  // Invoked after 100 milliseconds
  console.log(value); // 5
});

var stats = deferred.profileEnd(); // End profiling
console.log(stats.log);
```

Output is:
```
true
------------------------------------------------------------
Deferred usage statistics:

2 Total promises initialized
2 Initialized as Unresolved
0 Initialized as Resolved

Unresolved promises were initialized at:
1 at /home/node/Documents/learn/scrapping/index.js:7:15
1 at Object.<anonymous> (/home/node/Documents/learn/scrapping/index.js:32:1)
------------------------------------------------------------

5

```

Please let me know what's the issue.

**Comment by medikoo** [comment]
@anjil all is as expected, and there's no issue. See it's "__Initialized__ as  Unresolved", not "Never resolved". It's those that never resolve that signal an issue.

_All promises created with `deferred()` and then resolved with either `deferred.resolve` and `deferred.reject` are understood as "Unresolved at initialization"._

_To have promise resolved at initialization, you would have to create resolved promise right away via e.g. `deferred('foo')`, which will create promise that's already resolved with foo value._
