### ISSUE TITLE
Is it possible to make a drop-in replacement for Q?

### ISSUE THREAD

**Issue by seiyria** [medikoo/deferred#37]
I've been doing some research on Qs performance and it seems abysmal -- it's the #1 problem in my app, CPU-wise. I would really like to try out another solution, but deferred doesn't seem to be something I can just drop in and test.

Is it possible to make deferred have an extension for Q so a dropin replacement is more feasible? I'd rather not make testing something a day-long affair if possible.

**Comment by medikoo** [comment]
Both projects provide same functionalities, but at some points their API's differ, so what you request will demand writing some kind of `Q` mock, that internally will propagate everything to `deferred` functions.

At this point I don't plan on writing one, but if you want to, go for it. Probably `deferred-q` would make good package name. Still, I guess it might take about same time for you to refactor your existing project.

I'm going to close this issue, but if you have any specific questions concerning preparing such utility or migration feel free to ask here.

**Comment by seiyria** [comment]
It's a low priority for me also, I was just hoping there was something like this in existence already. If I find my CPU usage being problematic I will definitely be doing this first. Thanks! 

I would probably opt for the mock solution, because I could more easily do a find-and-replace-all on that, than it would be to replace all of the Q calls in my project. Plus then if I really needed to, I could switch back more easily.
