### ISSUE TITLE
No file name, line number or stack trace during error

### ISSUE THREAD

**Issue by andrewschools** [medikoo/deferred#41]
Hello - 

When using done(), during an error I am not getting any file name, line number or stack trace, just the error message.  For example, 

```javascript
doSomething.then(function(result) {
    console.log(result);
}).done(function(result) {
    console.log(result)
}, function(err) {
    console.error(err);
});
```
If an error occurs, I only get the following printed to the console:

```javascript
[TypeError: Object prototype may only be an Object or null]
```
There are no other parameters sent to this function. 

Is there anyway to obtain the file name, line number and stack trace of the error? 

Thank you,
Andrew Schools

**Comment by medikoo** [comment]
Stack trace is accessible on `error.stack` property (it's how native JavaScript API work)

**Comment by andrewschools** [comment]
Thank you.
